DATASET:
  PART_COUNT: 1
  SIZE: 60000
  # PATH: /data/datasets/mnist/tfrecords/mnist-r%02d.tfrecords.%03d
  PATH: /data/datasets/mnist32/tfrecords/mnist-r%02d.tfrecords.%03d
  PATH_TEST: /data/datasets/mnist32/tfrecords/mnist_test-r%02d.tfrecords.%03d
  MAX_RESOLUTION_LEVEL: 5
  FLIP_IMAGES: False
MODEL:
  LATENT_SPACE_SIZE: 32
  LAYER_COUNT: 4
  MAX_CHANNEL_COUNT: 256
  START_CHANNEL_COUNT: 64
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 4
  CHANNELS: 1
OUTPUT_DIR: mnist_results
TRAIN:
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 10
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 60
  LOD_2_BATCH_8GPU: [128, 128, 128,   64]
  LOD_2_BATCH_4GPU: [128, 128, 128,   64]
  LOD_2_BATCH_2GPU: [128, 128, 128,   64]
  LOD_2_BATCH_1GPU: [128, 128, 128,   64]

  LEARNING_RATES: [0.0015,  0.0015,   0.0015,   0.0015]
